name: audit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.2  

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Install dependencies
      run: go mod tidy

    - name: Run gofmt-action
      uses: Jerome1337/gofmt-action@v1.0.5
      with:
        gofmt-path: ./
        gofmt-flags: -l

    - name: Check formatting
      run: |
        UNFORMATTED_FILES=$(gofmt -l .)
        if [ -n "$UNFORMATTED_FILES" ]; then
          echo "The following files are not formatted correctly:"
          echo "$UNFORMATTED_FILES"
          exit 1
        else
          echo "All files are formatted correctly."
        fi

    - name: Run go vet
      run: go vet ./...

