name: audit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.2  

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Install dependencies
      run: go mod tidy 

    - name: Run gofmt-action
      uses: Jerome1337/gofmt-action@v1.0.5
      with:
        gofmt-path: .
        gofmt-flags: -l -d

    - name: Check formatting
      run: |
        unformatted=$(gofmt -l .)
        if [ -n "$unformatted" ]; then
          echo "All the following files are not correctly formatted"
          echo "$unformatted"
          exit 1
        else
          echo "All files are formatted correctly."
        fi

    - name: Run go vet
      run: go vet ./...

