name: check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.2

    - name: Check Go version
      run: go version

    - name: Install dependencies
      run: go mod tidy

    - name: Verify dependencies
      run: go mod verify

    - name: Run gofmt-action
      uses: Jerome1337/gofmt-action@v1.0.5
      with:
        gofmt-flags: -l -d

    - name: Run go vet
      run: go vet ./...

    - name: Run tests
      run: go test -v -race ./...
